---
platform_id: "P019"
platform_type: "production"
env_type: "production"
region: "IOM"

ipAddresses:
  gameflex: "REPLACE_WITH_IOM_P019_GAMEFLEX_IP"
  backoffice: "REPLACE_WITH_IOM_P019_BACKOFFICE_IP"