---
cloudflare_network_settings:
  ipv6: true
  websockets: true
  pseudo_ipv4: "off"
  ip_geolocation: true
  
  http3: true
  quic: true
  zero_rtt: true
  
  connection:
    min_tls_version: "1.2"
    tls_1_3: "on"
    opportunistic_encryption: "on"
    
  proxy:
    orange_to_orange: false
    opportunistic_onion: false

cloudflare_network_ip_geolocation:
  enabled: true

cloudflare_network_health_checks_enabled: true
cloudflare_network_health_checks_defaults:
  type: "https"
  path: "/gamelaunch/api/v2.0/heartbeat/{{ platform_id }}/IFO/20/gameProviders"
  port: 443
  interval: 60
  retries: 2
  timeout: 5
  expected_codes: "200"
  check_regions: ["WEU", "ENAM"]
