---
cloudflare_network_settings:
  ipv6: true
  websockets: true
  pseudo_ipv4: "add_header"
  ip_geolocation: true
  http3: true
  quic: true
  zero_rtt: true
  connection:
    min_tls_version: "1.2"
    tls_1_3: "on"
    opportunistic_encryption: "on"
  proxy:
    orange_to_orange: false
    opportunistic_onion: false
