---
rabbitmq_admin_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  62663262353162346135376362616661346264656238346539353533643763333339363663333636
  3131383632656138633635626239393762613230356664350a393338626162346236373038356438
  64303536356639663265313239313639626637383930343763653435396336646532613765626333
  6132366630666330640a323136316539376366643136643337616637363237373564363934393732
  6535
rabbitmq_pugsdist_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  63336439653661663362326434323030303865356633356366623339366236343362373538643036
  3532383035646634333534366463383630666330663363380a363963646461616132646631373938
  38666237366435636539613732343230373263306363666236613237326636393730306536663966
  3964363965353635620a316636613432326430623133636561326534363234623461383033373238
  61393762616436656639373330313737313562323363313964303138326264663164
rabbitmq_pugspub_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  66626263313232656563353538613135323731356633383965343534343239306261346565666635
  3733386362316433313437313861353136386232383332390a653030356338343261383734363265
  61303765386133663863366362346638613764373763646135646532636664366363666564656534
  3938306162336164390a656439663735363332363937363234306662636636373439653665646239
  31643363653033373238363432303437383938646465363135666535306337393838
rabbitmq_s009user_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  32306435613231323634633338626366353036623962366331316364313061356361303235626637
  6133646565393962396433623630326566306135366337660a666365626634396331613934386231
  34333932343935363135613537383839373736363162353861636466623962613832346533306231
  3962333238393165320a316335333062333630356538636436306236666634313737303366396262
  30633033343466316263646664393533346633646234343232633765393631633836
rabbitmq_t009user_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  33643366323165316461666234303630306565393066623064363033373439623936316130383636
  3838363131653536383230306430323261303834623434320a643331393535313035313639333836
  63626537316663393337623639613565333138383531666336316236306437666335373532343865
  3264356366663839380a393937313836303334313738653665623563356331653262663931333936
  63376131393438613035356465316236356433303032356530363032313833396661
rabbitmq_p009user_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  35363730343232393061656163316264396338373532623031643438613335353435353837356263
  3434323162623361646464333239373134616637303463300a366637353534303162626264393839
  33613839346437373434373434323262393033333265333265303365383964373036306531636536
  3463353837366636360a633638353363306431396235366234313139646562623931376164396633
  63343933646631663563323966336231636531316235646165626231383763653836