---
awx_host: "http://{{ groups['ansible'][0] }}:{{ hostvars[groups['ansible'][0]]['ansible_port'] | default(80) }}"
awx_username: "awxcloudflare"
awx_validate_certs: true
awx_organization: "{{ awx_organization_override | default('Default') }}"
awx_project_name: "Cloudflare-DevOps"
awx_project_description: "Cloudflare DNS and configuration management from Git"
awx_project_scm_type: "git"
awx_project_scm_url: "https://github.com/T-Hlophe-gameflex/TESTING-REPO.git"
awx_project_scm_branch: "main"
awx_project_scm_clean: true
awx_project_scm_delete_on_update: true
awx_project_scm_update_on_launch: true
awx_project_scm_update_cache_timeout: 0
awx_project_credential: ""  
awx_inventory_name: "TEST"
awx_credential_type_name: "AWX Cluster Authentication"
awx_credential_type_description: "Credentials for connecting to remote AWX/Tower clusters"
awx_create_credential_type: true  
awx_create_awx_credential: false  
awx_cluster_credential_name: "AWX-Cluster-Access"
awx_template_name: "Cloudflare-Deployment"
awx_playbook_path: "cloudflare.yml"
survey_enabled: true
ask_credential_on_launch: false  
cloudflare_credential_name: "Cloudflare-API-Token"
cloudflare_api_url: "https://api.cloudflare.com/client/v4"
